### ISSUE TITLE
add K Dimensional Tree

### ISSUE THREAD

**Issue by farQtech** [farQtech/Data-Structures#12]
Add interface and implementation for K Dimensional Tree in c# [more info here](https://en.wikipedia.org/wiki/K-d_tree)

**Comment by atrievel** [comment]
@farQtech - I'd like to take this on if possible. Just a few questions:

- What methods would you to be implemented (sort, search, AddNode, DeleteNode, etc.)
- What are the inputs that will allow the tree to be built?
- What type of tree? (i.e. BinaryTree)

**Comment by farQtech** [comment]
Yes!, Please go ahead. To answer your questions, you can implement any method you want but implement atleast three. Take any input you want and use any kind of tree you like. Later I'll add some more specific issues to cover this topic.
