### ISSUE TITLE
fix badges

### ISSUE THREAD

**Issue by farQtech** [farQtech/Data-Structures#23]
the badge on readme.md shows wrong numbers.

![image](https://user-images.githubusercontent.com/31050786/94947090-b4684700-04fa-11eb-9bbd-de9450be9b0e.png)

**Comment by adityaa-p** [comment]
Can I work on this?

**Comment by farQtech** [comment]
@APalpattuwar7 Yes!, please go ahead.

**Comment by adityaa-p** [comment]
I can see correct URL's being used for 'Stars' and 'Watchers' in Readme.md file (Had to change for 'Forks' only). Still can't see correct numbers. Is there anything which I am missing?

**Comment by farQtech** [comment]
Try readding the same badges, that'll solve the problem for now. For some reason the badges are just not picking the updated values

**Comment by farQtech** [comment]
Closed by mistake. My bad!
