### ISSUE TITLE
Kindly add Hacktoberfest topic in this Repository 

### ISSUE THREAD

**Issue by Sahastracookcoder1** [farQtech/Data-Structures#26]
There's an update by Hacktoberfest that PR will be accepted if and only hacktoberfest topic is mentioned and when I reach to your Repository it's not mentioned Kindly do the same.

For more details about Update and how to add topic kindly visit below link.
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by farQtech** [comment]
@Sahastracookcoder1 Thanks for reminding. Added hacktoberfest topic
