### ISSUE TITLE
Add an implementation for Segment Tree in c#.

### ISSUE THREAD

**Issue by farQtech** [farQtech/Data-Structures#28]
Implement [Segment Tree](https://en.wikipedia.org/wiki/Segment_tree) and make a PR to this repo.

**Comment by MHFarooqui** [comment]
please assign this to me.

**Comment by farQtech** [comment]
sure, Thanks @MHFarooqui

**Comment by farQtech** [comment]
Thanks to @MHFarooqui 's contribution, this issue can be closed.
