### ISSUE TITLE
Add a contents/lookup file

### ISSUE THREAD

**Issue by farQtech** [farQtech/Data-Structures#3]
As more Ds implementations are added to the repo, It'll be harder to keep track of and find a particular implementation. This can be easily solved by adding a lookup file that contains a link to each implementation.

Add that file inside docs/

**Comment by abrahman07** [comment]
I would like work on this issue

**Comment by farQtech** [comment]
Sure! go ahead. get your self [registered ](https://hacktoberfest.digitalocean.com/) if haven't already.

**Comment by farQtech** [comment]
Also, add the list in the Readme.md in the root folder. you are free to choose any style but to give you an idea I'm attaching this snapshot

![image](https://user-images.githubusercontent.com/31050786/94415420-20fde180-019b-11eb-9c93-95deb9405bb6.png)
