### ISSUE TITLE
Organize files and folders

### ISSUE THREAD

**Issue by farQtech** [farQtech/Data-Structures#31]
This repo contains a hand full of files but these files are not organized, please organize these files in a semantic manner and make a PR to this repo.

**Comment by MHFarooqui** [comment]
please assign this to me.

**Comment by farQtech** [comment]
Sure, Thanks @MHFarooqui

**Comment by farQtech** [comment]
@MHFarooqui please update folder structure as your contribution for dequeue is unorganized

**Comment by akshpnwr** [comment]
can i take this?

**Comment by farQtech** [comment]
@akshpnwr  Sure. Go ahead

**Comment by akshpnwr** [comment]
You can close this issue now.
