### ISSUE TITLE
add graph implementation

### ISSUE THREAD

**Issue by farQtech** [farQtech/Data-Structures#5]
Add implementation for the graph in cs also add one or two graph traversal algorithm implementation such as BFS, DFS, etc.

**Comment by Ajit-53** [comment]
i would like to work on this.Can you please assign me?

**Comment by Sahastracookcoder1** [comment]
Hi @farQtech 

I would like to do this. Can you assign me to the same as a part of Hactoberfest?

**Comment by farQtech** [comment]
Sure!

**Comment by jhoserpacheco** [comment]
Hi @farQtech 
I would like to do this. Graph traversal algorithm in java or c++, can you assign me?

**Comment by farQtech** [comment]
Sorry @jhoserpacheco , this repo is exclusive for cs implementation.
