### ISSUE TITLE
Add implementation for CircularBuffer

### ISSUE THREAD

**Issue by Squirkyy** [farQtech/Data-Structures#7]
Add implementation for circular buffer.

PS: I volunteer for that 😉

**Comment by farQtech** [comment]
Great!, Assigned to you 🙂

**Comment by Squirkyy** [comment]
#13 Here you go 😊
But I should wait till October 1st for it to count right? Or how does it work? 🤔

**Comment by farQtech** [comment]
yes!, you should wait till oct 1st. refer the FAQs [here](https://hacktoberfest.digitalocean.com/faq/)
